import java.awt.Cursor;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//@author Timur

public class FramePrihodItem extends javax.swing.JFrame {

    private Connection conn;
    private Statement stmt;
    private ResultSet rs;    
    
    //String userName = "root";
    //String password = "admin";
    //String url = "jdbc:MySQL://localhost";
    
    public FramePrihodItem() {
        initComponents();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTop = new javax.swing.JPanel();
        tfFIO = new javax.swing.JTextField();
        tfIDzak = new javax.swing.JTextField();
        tfLCod = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        tfPrim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panBottom = new javax.swing.JPanel();
        bbSaveCsv = new javax.swing.JButton();
        tfSumma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbIsp = new javax.swing.JLabel();
        lbIsp1 = new javax.swing.JLabel();
        panCentr = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabZakazItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                PrihodAktiv(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panTop.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                panTopComponentAdded(evt);
            }
        });
        panTop.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panTopComponentShown(evt);
            }
        });

        tfFIO.setEditable(false);
        tfFIO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfFIO.setForeground(new java.awt.Color(0, 0, 153));

        tfIDzak.setEditable(false);
        tfIDzak.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIDzak.setForeground(new java.awt.Color(0, 0, 153));
        tfIDzak.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfIDzak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDzakActionPerformed(evt);
            }
        });

        tfLCod.setEditable(false);
        tfLCod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfLCod.setForeground(new java.awt.Color(0, 0, 153));
        tfLCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfDate.setEditable(false);
        tfDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfDate.setForeground(new java.awt.Color(0, 0, 153));
        tfDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfPrim.setEditable(false);
        tfPrim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPrim.setForeground(new java.awt.Color(0, 0, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Примечание:");

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panTopLayout.createSequentialGroup()
                        .addComponent(tfIDzak, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTopLayout.createSequentialGroup()
                        .addComponent(tfLCod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFIO, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfPrim))
                .addContainerGap())
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIDzak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        bbSaveCsv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bbSaveCsv.setForeground(new java.awt.Color(0, 0, 153));
        bbSaveCsv.setText("Cохранить в csv");
        bbSaveCsv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbSaveCsv.setEnabled(false);
        bbSaveCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbSaveCsvActionPerformed(evt);
            }
        });

        tfSumma.setEditable(false);
        tfSumma.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tfSumma.setForeground(new java.awt.Color(0, 0, 153));
        tfSumma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSumma.setCaretColor(new java.awt.Color(0, 0, 153));
        tfSumma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSummaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Сумма");

        lbIsp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbIsp.setForeground(new java.awt.Color(0, 0, 153));
        lbIsp.setText("Исп");

        lbIsp1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbIsp1.setForeground(new java.awt.Color(0, 0, 153));
        lbIsp1.setText("Исполнитель:");

        javax.swing.GroupLayout panBottomLayout = new javax.swing.GroupLayout(panBottom);
        panBottom.setLayout(panBottomLayout);
        panBottomLayout.setHorizontalGroup(
            panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBottomLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbIsp1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbIsp, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(bbSaveCsv)
                .addContainerGap())
        );
        panBottomLayout.setVerticalGroup(
            panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbSaveCsv)
                    .addComponent(tfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lbIsp)
                    .addComponent(lbIsp1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panCentr.setPreferredSize(new java.awt.Dimension(900, 500));

        tabZakazItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabZakazItem.setForeground(new java.awt.Color(0, 0, 153));
        tabZakazItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "№ пп", "Артикул", "Наименование", "Цена", "Кол-во", "Сумма"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabZakazItem.setRowHeight(34);
        tabZakazItem.setRowMargin(3);
        tabZakazItem.setShowGrid(true);
        tabZakazItem.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabZakazItemComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabZakazItem);
        if (tabZakazItem.getColumnModel().getColumnCount() > 0) {
            tabZakazItem.getColumnModel().getColumn(0).setResizable(false);
            tabZakazItem.getColumnModel().getColumn(1).setResizable(false);
            tabZakazItem.getColumnModel().getColumn(2).setPreferredWidth(400);
            tabZakazItem.getColumnModel().getColumn(3).setResizable(false);
            tabZakazItem.getColumnModel().getColumn(4).setResizable(false);
            tabZakazItem.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout panCentrLayout = new javax.swing.GroupLayout(panCentr);
        panCentr.setLayout(panCentrLayout);
        panCentrLayout.setHorizontalGroup(
            panCentrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCentrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        panCentrLayout.setVerticalGroup(
            panCentrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCentrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panCentr, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(panBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCentr, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDzakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDzakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDzakActionPerformed

    private void panTopComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panTopComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panTopComponentAdded

    private void panTopComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panTopComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_panTopComponentShown

    private void bbSaveCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbSaveCsvActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String nameFiles = "temp\\Накладная приход_"+tfIDzak.getText()+".csv";
        String fText = "№ зак.;"+tfIDzak.getText()+";Дата: "+tfDate.getText()+";;;;\n";
        fText = fText + "Личный №;"+tfLCod.getText()+";Исполнитель: "+lbIsp.getText()+";;;;\n";
        fText = fText +"\n";
        fText = fText + "№ пп;Артикул;Наименование;Цена;Кол-во;Сумма;\n";

        for (int i = 0; i < tabZakazItem.getRowCount(); i++) {
            for (int k = 0; k < 6; k++) {
                fText = fText + tabZakazItem.getValueAt(i, k).toString() + ";";
            }
            fText = fText + "\n";
        }
        fText = fText + ";;;;;" + tfSumma.getText() + ";\n";

        try {
            File file = new File(nameFiles);
            file.delete();
            file.createNewFile();

            try (FileWriter writer = new FileWriter(file)) {
                writer.write(fText);
                writer.close();

            } catch (IOException e) {
                System.out.println("Ошибка-1 при записи в файл");
                //e.printStackTrace();
            }

            System.out.println("Текст успешно записан в файл.");
        } catch (IOException e) {
            System.out.println("Ошибка-2 при записи в файл");
            //e.printStackTrace();
        }

        String infostroka = "Файл:\n\n" + nameFiles + "\n\ncоздан успешно!";
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, infostroka);
    }//GEN-LAST:event_bbSaveCsvActionPerformed

    private void tfSummaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSummaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSummaActionPerformed

    private void tabZakazItemComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabZakazItemComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tabZakazItemComponentShown

    private void PrihodAktiv(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PrihodAktiv
        // TODO add your handling code here:
        try {
            tfIDzak.setText(Integer.toString(NewJFrameMainMyservisProg.IdZak));
                        
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();

                conn = DriverManager.getConnection(NewJFrameMainMyservisProg.urlHostBD, NewJFrameMainMyservisProg.userNameBD, NewJFrameMainMyservisProg.passwordBD);
                stmt = conn.createStatement();
                String query = "select date_zak,lcod,fio,sum_zak,isp,prim from myservis.prihod where id_zak="+NewJFrameMainMyservisProg.IdZak;
                rs = stmt.executeQuery(query);

                while (rs.next()) {
                    String sLCod = rs.getString("lcod");
                    String sDate = rs.getString("date_zak");
                    String fio = rs.getString("fio");
                    //String sum_zak = rs.getString("sum_zak");
                    String isp = rs.getString("isp");
                    String prim = rs.getString("prim");

                    tfLCod.setText(sLCod);
                    tfFIO.setText(fio);
                    tfDate.setText(sDate);
                    tfPrim.setText(prim);
                    lbIsp.setText(isp);
                }
                rs.close();

                int SumZak = 0;
                DefaultTableModel dtm = (DefaultTableModel) tabZakazItem.getModel();
                dtm.getDataVector().removeAllElements(); // удаляем все строки

                query = "select artikul,towar,cen,kol from myservis.prihod_item where id_zak="+NewJFrameMainMyservisProg.IdZak;
                rs = stmt.executeQuery(query);
                int i = 0;
                while (rs.next()) {
                    i = i + 1;
                    int artikul = rs.getInt("artikul");
                    String towar = rs.getString("towar");
                    int cen = rs.getInt("cen");
                    int kol = rs.getInt("kol");
                    tabZakazItem.setRowHeight(i, 50);
                    dtm.addRow(new Object[]{i, artikul,towar,cen,kol,cen*kol});
                    SumZak = SumZak + cen*kol;
                }

                rs.close();
                stmt.close();

                String sZak = Integer.toString(SumZak);
                tfSumma.setText(sZak);

                if (i == 0) {
                    dtm.getDataVector().removeAllElements(); // удаляем все строки
                    dtm.addRow(new Object[]{"", "", "", "", "", "", "", "", "", ""});
                    JFrame jfInfo = new JFrame();
                    JOptionPane.showMessageDialog(jfInfo, "Приходов не обнаружено!");
                } else {
                }

            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
                System.err.println("Cannot connect to database server");
            } finally {
                if (conn != null) {
                    try {
                        System.out.println("n***** Let terminate the Connection *****");
                        conn.close();
                        System.out.println("Database connection terminated... ");
                    } catch (SQLException ex) {
                        System.out.println("Error in connection termination!");
                    }
                }
            }
        bbSaveCsv.setEnabled(true);
        panCentr.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_PrihodAktiv

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrihodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrihodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrihodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrihodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrihodItem().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbSaveCsv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIsp;
    private javax.swing.JLabel lbIsp1;
    private javax.swing.JPanel panBottom;
    private javax.swing.JPanel panCentr;
    private javax.swing.JPanel panTop;
    private javax.swing.JTable tabZakazItem;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfFIO;
    private javax.swing.JTextField tfIDzak;
    private javax.swing.JTextField tfLCod;
    private javax.swing.JTextField tfPrim;
    private javax.swing.JTextField tfSumma;
    // End of variables declaration//GEN-END:variables


}
